---
title: Clase Manometer
---
flowchart TB
    U1["Inicio update"]
    U2["Obtener via1"]
    U3["Buscar node"]
    U4["Actualizar pressure"]
    U5["Actualizar color"]
    U6["Fin update"]

    U1 --> U2 --> U3 --> U4 --> U5 --> U6
